"""bot_trade tracks resolve attempts and not_found

Revision ID: 09adb10cc3da
Revises: f24fea00558c
Created: 2026-08-31 00:05:58.833523
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '09adb10cc3da'
down_revision = 'f24fea00558c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolve_attempts', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_trade', schema=None) as batch_op:
        batch_op.drop_column('resolve_attempts')

    # ### end Alembic commands ###
