"""research tables

Revision ID: 3f867a5f1322
Revises: 5e5e371b1189
Created: 2026-08-28 16:44:46.675144
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision = '3f867a5f1322'
down_revision = '5e5e371b1189'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_gex0dte_hour',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('hour_cst', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('net_gex', sa.Float(), nullable=False),
    sa.Column('call_gex', sa.Float(), nullable=True),
    sa.Column('put_gex', sa.Float(), nullable=True),
    sa.Column('spot', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=8), nullable=True),
    sa.Column('flip', sa.Float(), nullable=True),
    sa.Column('call_wall', sa.Float(), nullable=True),
    sa.Column('put_wall', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_gex0dte_hour')),
    sa.UniqueConstraint('trade_date', 'hour_cst', name='uq_research_gex0dte_date_hour')
    )
    op.create_table('research_pusher_heartbeat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session', sa.String(length=16), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=True),
    sa.Column('wall_ms', sa.BigInteger(), nullable=True),
    sa.Column('mono_ms', sa.BigInteger(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_pusher_heartbeat'))
    )
    with op.batch_alter_table('research_pusher_heartbeat', schema=None) as batch_op:
        batch_op.create_index('ix_research_pusher_received', ['received_at'], unique=False)

    op.create_table('research_signal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('book', sa.String(length=8), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.Column('combo', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('accuracy_pct', sa.Float(), nullable=True),
    sa.Column('bar_time', sa.String(length=64), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('raw', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_signal')),
    sa.UniqueConstraint('external_id', name='uq_research_signal_external')
    )
    with op.batch_alter_table('research_signal', schema=None) as batch_op:
        batch_op.create_index('ix_research_signal_book_time', ['book', 'logged_at'], unique=False)
        batch_op.create_index('ix_research_signal_ticker_time', ['ticker', 'logged_at'], unique=False)

    op.create_table('research_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_snapshot')),
    sa.UniqueConstraint('kind', 'snapshot_date', name='uq_research_snapshot_kind_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_snapshot')
    with op.batch_alter_table('research_signal', schema=None) as batch_op:
        batch_op.drop_index('ix_research_signal_ticker_time')
        batch_op.drop_index('ix_research_signal_book_time')

    op.drop_table('research_signal')
    with op.batch_alter_table('research_pusher_heartbeat', schema=None) as batch_op:
        batch_op.drop_index('ix_research_pusher_received')

    op.drop_table('research_pusher_heartbeat')
    op.drop_table('research_gex0dte_hour')
    # ### end Alembic commands ###
