"""bot_trade contracts is fractional

Revision ID: 56f33b1be891
Revises: 7c21b4e903aa
Created: 2026-08-30 00:12:58.509151
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '56f33b1be891'
down_revision = '7c21b4e903aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_trade', schema=None) as batch_op:
        batch_op.alter_column('contracts',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_trade', schema=None) as batch_op:
        batch_op.alter_column('contracts',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
