"""pusher heartbeat natural key

Revision ID: 7c21b4e903aa
Revises: 3f867a5f1322

The heartbeat table was created append-only with no natural key, on the
reasoning that "append-only" meant duplicates were impossible. It does not:
append-only describes how the table is written at runtime, and says nothing
about an ingest pass running twice. Re-running the research importer copied
every row a second time, and the duplicates were indistinguishable from a
pusher that genuinely fired twice in one cycle -- destroying the exact signal
this table exists to carry.

(session, seq) identifies one push cycle: seq restarts at 1 per session, and
session is per browser document. Verified unique across all 708 source rows
before this constraint was written.

This migration deletes duplicate cycles (keeping the lowest id of each) and
then adds the constraint, in that order, because the constraint cannot be
added while the duplicates exist.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "7c21b4e903aa"
down_revision = "3f867a5f1322"
branch_labels = None
depends_on = None

# Inlined rather than imported. A migration must keep running when the model
# it was written against has moved on; reaching into app code would make this
# file's behaviour depend on a future version of that code.
_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def upgrade() -> None:
    # Order matters: dedupe first, or the constraint cannot be created.
    op.execute("""
        DELETE FROM research_pusher_heartbeat
         WHERE id NOT IN (SELECT MIN(id)
                            FROM research_pusher_heartbeat
                           GROUP BY session, seq)
    """)
    # naming_convention must be passed here too: SQLite rebuilds the table,
    # and without it the recreated constraints get autogenerated names that no
    # later migration can address by name.
    with op.batch_alter_table("research_pusher_heartbeat",
                              naming_convention=_CONVENTION) as batch:
        batch.create_unique_constraint(
            "uq_research_pusher_session_seq", ["session", "seq"])


def downgrade() -> None:
    with op.batch_alter_table("research_pusher_heartbeat",
                              naming_convention=_CONVENTION) as batch:
        batch.drop_constraint("uq_research_pusher_session_seq", type_="unique")
