"""baseline

Revision ID: aff06ddaba7f
Revises: 
Created: 2026-08-28 08:26:56.770778
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'aff06ddaba7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_lease',
    sa.Column('resource_key', sa.String(length=160), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('holder', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('resource_key', name=op.f('pk_execution_lease'))
    )
    op.create_table('risk_heartbeat',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('last_pass_at', sa.DateTime(), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_risk_heartbeat'))
    )
    op.create_table('signal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal')),
    sa.UniqueConstraint('book', 'external_id', name='book_external')
    )
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.create_index('ix_signal_book_logged', ['book', 'logged_at'], unique=False)

    op.create_table('tenant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_algo', sa.String(length=32), nullable=False),
    sa.Column('password_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status in ('active','suspended')", name=op.f('ck_tenant_status_known')),
    sa.CheckConstraint('length(slug) > 0', name=op.f('ck_tenant_slug_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant')),
    sa.UniqueConstraint('email', name=op.f('uq_tenant_email')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenant_slug'))
    )
    op.create_table('bot_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('bot_key', sa.String(length=32), nullable=False),
    sa.Column('bot_version', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('bankroll', sa.Float(), nullable=True),
    sa.Column('target_pct', sa.Float(), nullable=True),
    sa.Column('stop_pct', sa.Float(), nullable=True),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("mode in ('paper','live')", name=op.f('ck_bot_run_mode_known')),
    sa.CheckConstraint("status in ('running','stopped','crashed','killed')", name=op.f('ck_bot_run_status_known')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_bot_run_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_run'))
    )
    with op.batch_alter_table('bot_run', schema=None) as batch_op:
        batch_op.create_index('ix_bot_run_tenant_bot_started', ['tenant_id', 'bot_key', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_run_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('bot_trade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('bot_key', sa.String(length=32), nullable=False),
    sa.Column('bot_version', sa.String(length=16), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('contracts', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('fee_checked_at', sa.DateTime(), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status in ('open','closed','cancelled')", name=op.f('ck_bot_trade_status_known')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_bot_trade_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_trade')),
    sa.UniqueConstraint('tenant_id', 'bot_key', 'external_id', name='tenant_bot_external')
    )
    with op.batch_alter_table('bot_trade', schema=None) as batch_op:
        batch_op.create_index('ix_bot_trade_tenant_bot_opened', ['tenant_id', 'bot_key', 'opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_trade_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('execution_attempt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('intent', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('venue_order_id', sa.String(length=64), nullable=True),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("intent in ('open','open_contract','close','sweep','set_target','carry_over','bot_start','bot_stop','bot_kill','bot_sync')", name=op.f('ck_execution_attempt_intent_known')),
    sa.CheckConstraint("status in ('in_flight','succeeded','failed')", name=op.f('ck_execution_attempt_status_known')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_execution_attempt_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_attempt')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='tenant_key'),
    sa.UniqueConstraint('tenant_id', 'request_fingerprint', name='tenant_fingerprint')
    )
    with op.batch_alter_table('execution_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_attempt_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('venue_sandbox', sa.Boolean(), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('occ_symbol', sa.String(length=32), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration', sa.String(length=10), nullable=False),
    sa.Column('delta_at_entry', sa.Float(), nullable=True),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('buy_pct', sa.Float(), nullable=False),
    sa.Column('tolerance_pct', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('tp_pct', sa.Float(), nullable=False),
    sa.Column('sl_pct', sa.Float(), nullable=False),
    sa.Column('tp_price', sa.Float(), nullable=True),
    sa.Column('sl_price', sa.Float(), nullable=True),
    sa.Column('buy_order_id', sa.String(length=64), nullable=True),
    sa.Column('tp_order_id', sa.String(length=64), nullable=True),
    sa.Column('stop_order_id', sa.String(length=64), nullable=True),
    sa.Column('stop_protection', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("option_type in ('call','put')", name=op.f('ck_position_option_type_known')),
    sa.CheckConstraint("status in ('pending','open','tp_filled','sl_filled','closed','failed')", name=op.f('ck_position_status_known')),
    sa.CheckConstraint("stop_protection in ('pending','venue_resting','monitored_only')", name=op.f('ck_position_stop_protection_known')),
    sa.CheckConstraint('contracts > 0', name=op.f('ck_position_contracts_positive')),
    sa.CheckConstraint('sl_pct > 0 and sl_pct < 100', name=op.f('ck_position_sl_in_range')),
    sa.CheckConstraint('tp_pct > 0', name=op.f('ck_position_tp_positive')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_position_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position'))
    )
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_position_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index('ix_position_tenant_symbol_status', ['tenant_id', 'occ_symbol', 'status'], unique=False)

    op.create_table('tenant_credential',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('venue', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.Column('rotated_by', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("venue in ('tradier','tradier_sandbox','kalshi')", name=op.f('ck_tenant_credential_venue_known')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant_credential_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_credential')),
    sa.UniqueConstraint('tenant_id', 'venue', 'label', name='tenant_venue_label')
    )
    with op.batch_alter_table('tenant_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_credential_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_world_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('world_key', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant_world_access_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_world_access')),
    sa.UniqueConstraint('tenant_id', 'world_key', name='tenant_world')
    )
    with op.batch_alter_table('tenant_world_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_world_access_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('wellness_profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('age_band', sa.String(length=16), nullable=True),
    sa.Column('ethnicity', sa.String(length=64), nullable=True),
    sa.Column('diet', sa.String(length=64), nullable=True),
    sa.Column('style', sa.String(length=32), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_wellness_profile_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wellness_profile')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_wellness_profile_tenant_id'))
    )
    op.create_table('tenant_secret_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action in ('created','rotated','revoked','verified')", name=op.f('ck_tenant_secret_audit_action_known')),
    sa.ForeignKeyConstraint(['credential_id'], ['tenant_credential.id'], name=op.f('fk_tenant_secret_audit_credential_id_tenant_credential'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant_secret_audit_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_secret_audit'))
    )
    with op.batch_alter_table('tenant_secret_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_secret_audit_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('wellness_goal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['wellness_profile.id'], name=op.f('fk_wellness_goal_profile_id_wellness_profile'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_wellness_goal_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wellness_goal')),
    sa.UniqueConstraint('profile_id', 'position', name='profile_goal_order')
    )
    with op.batch_alter_table('wellness_goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wellness_goal_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wellness_goal_tenant_id'))

    op.drop_table('wellness_goal')
    with op.batch_alter_table('tenant_secret_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_secret_audit_tenant_id'))

    op.drop_table('tenant_secret_audit')
    op.drop_table('wellness_profile')
    with op.batch_alter_table('tenant_world_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_world_access_tenant_id'))

    op.drop_table('tenant_world_access')
    with op.batch_alter_table('tenant_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_credential_tenant_id'))

    op.drop_table('tenant_credential')
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_index('ix_position_tenant_symbol_status')
        batch_op.drop_index('ix_position_tenant_status')
        batch_op.drop_index(batch_op.f('ix_position_tenant_id'))

    op.drop_table('position')
    with op.batch_alter_table('execution_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_attempt_tenant_id'))

    op.drop_table('execution_attempt')
    with op.batch_alter_table('bot_trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_trade_tenant_id'))
        batch_op.drop_index('ix_bot_trade_tenant_bot_opened')

    op.drop_table('bot_trade')
    with op.batch_alter_table('bot_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_run_tenant_id'))
        batch_op.drop_index('ix_bot_run_tenant_bot_started')

    op.drop_table('bot_run')
    op.drop_table('tenant')
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.drop_index('ix_signal_book_logged')

    op.drop_table('signal')
    op.drop_table('risk_heartbeat')
    op.drop_table('execution_lease')
    # ### end Alembic commands ###
