"""risk_heartbeat tenant fk

Revision ID: affed5ed5671
Revises: aff06ddaba7f
Created: 2026-08-28 16:09:51.254559
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'affed5ed5671'
down_revision = 'aff06ddaba7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_heartbeat', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_risk_heartbeat_tenant_id_tenant'), 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_heartbeat', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_risk_heartbeat_tenant_id_tenant'), type_='foreignkey')

    # ### end Alembic commands ###
