"""bot_trade carries market, outcome and cash totals

Revision ID: f24fea00558c
Revises: 56f33b1be891
Created: 2026-08-30 23:11:23.263508
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'f24fea00558c'
down_revision = '56f33b1be891'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_title', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('outcome', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('entry_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exit_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fees_usd', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_trade', schema=None) as batch_op:
        batch_op.drop_column('fees_usd')
        batch_op.drop_column('exit_usd')
        batch_op.drop_column('entry_usd')
        batch_op.drop_column('outcome')
        batch_op.drop_column('market_title')

    # ### end Alembic commands ###
